-- Add all the new enum values to the existing enum
-- Note: Each ALTER TYPE command needs to be in its own transaction when adding enum values

ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'FINALIZADO EM ACORDO ANTES DA PERÍCIA';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'AGENDAR PERÍCIA';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'AGUARDANDO PERÍCIA';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'AGUARDANDO LAUDO';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'AGUARDANDO ESCLARECIMENTOS';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'LAUDO/ESCLARECIMENTOS ENTREGUES';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'SENTENÇA';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'RECURSO ORDINÁRIO';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'ACORDO APÓS REALIZAÇÃO DA PERÍCIA';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'CERTIDÃO DE TRÂNSITO EM JULGADO';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'SOLICITAÇÃO DE PAGAMENTO DE HONORÁRIOS';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'HONORÁRIOS RECEBIDOS';
ALTER TYPE pericia_status ADD VALUE IF NOT EXISTS 'REFAZER A PERÍCIA - ORDEM JUDICIAL';